```{r load-packages, message = FALSE}
library(plyr)
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
library(dplyr)
# library(glmnet)
```

```{r loading}
data12 <- haven::read_sav('C:/Users/user/OneDrive/University/Semester D/Advanced Data Analysis in R/Assignments/AP_Final_Project/Final_Project/child_risk_t12.sav')
data3 <- haven::read_sav('C:/Users/user/OneDrive/University/Semester D/Advanced Data Analysis in R/Assignments/AP_Final_Project/Final_Project/3rd assessment.sav')
```

```{r selection}
relevant_cols <- c('serial_number', 'ParentMeet', 'ParentPhone', 'FamilyTrust', 'FamilSupp',
                  'Mentor', 'MentorFreq', 'FormalMentor', 'PnimiaTrust', 'PnimiaSupp',
                  'HelpSeekInten1', 'HelpSeekInten2', 'V34', 'SenseCont1', 'SenseCont2',
                  'SenseCont3', 'SenseCont4', 'SenseCont5', 'SenseCont6', 'B.SUPPORT_1',
                  'B.SUPPORT_2', 'B.SUPPORT_3', 'B.SUPPORT_4', 'B.SUPPORT_5', 'B.SUPPORT_6',
                  'B.CONTACT.DURATION', 'B.HELP.MENTAL', 'B.HELP.MENTAL.DEGREE', 'B.HELP.RELATIONS',
                  'B.HELP.RELATIONS.DEGREE', 'B.HELP.NONPROFIT', 'B.HELP.NONPROFIT.DEGREE',
                  'B.MAIN.OCCUPATION_1', 'B.MAIN.OCCUPATION_8', 'B.MAIN.OCCUPATION_9',
                  'B.LONELY_1', 'B.LONELY_2', 'B.LONELY_3', 'B.LONELY_4', 'B.INTERNET.SUPPORT_3',
                  'B.INTERNET.SUPPORT_4', 'T3_SRH', 'T3job_no', 'T3A8.wp.160', 'T3T314.10',
                  'T3Adverse_Events_1', 'T3Adverse_Events_2', 'T3Adverse_Events_3',
                  'T3Adverse_Events_4', 'T3Adverse_Events_5', 'T3Adverse_Events_6',
                  'T3Adverse_Events_7', 'T3Adverse_Events_8', 'T3Adverse_Events_9',
                  'T3Adverse_Events_10', 'T3_ACE_1', 'T3_ACE_2', 'T3_ACE_3', 'T3_ACE_4', 'T3_ACE_5',
                  'T3_ACE_6', 'T3_ACE_7', 'T3_ACE_8', 'T3_ACE_9', 'T3housing_status',
                  'T3army_fullservice', 'T3civil_service', 'T3civilserv_full', 'T3helpneeded_1',
                  'T3helpneeded_2', 'T3helpneeded_3', 'T3helpneeded_4', 'T3helpneeded_5',
                  'T3helpneeded_6', 'T3helpneeded_7', 'T3helpneeded_8', 'T3helpneeded_9',
                  'T3_10.20', 'T3_10.120', 'T3_10.460_1', 'T3_10.460_2', 'T3_10.460_3',
                  'T3_10.460_4', 'T3_socialsupport_1', 'T3_socialsupport_2', 'T3_socialsupport_3',
                  'T3_socialsupport_4', 'T3_socialsupport_5', 'T3_socialsupport_6', 'T3_14.80',
                  'T3_life_satisfaction_1', 'T3_life_satisfaction_2', 'T3_life_satisfaction_3',
                  'T3_life_satisfaction_4', 'T3_life_satisfaction_5', 'T3_life_satisfaction_6',
                  'T3_life_satisfaction_7', 'T3_skills_1', 'T3_skills_2', 'T3_skills_3',
                  'T3_skills_4', 'T3_skills_5', 'T3_skills_6', 'T3_skills_7', 'T3_skills_8',
                  'T3_skills_9', 'T3_skills_10', 'T3_skills_11', 'T3_skills_12', 'T3_skills_13',
                  'T3_skills_14', 'T3_skills_15', 'T3_skills_16')

flip_scale <- function(df, col_name) {
  flip_factor <- max(df[col_name], na.rm = TRUE) + 1
  for (row in seq_len(nrow(df))) {
    if (is.na(df[row, col_name])) { next }
    df[row, col_name] <- flip_factor - ifelse(df[row, col_name] >= 1,
                                              round(df[row, col_name]), 1)
  }
  return(df)
}
flip_list <- c('ParentMeet', 'ParentPhone', 'T3_SRH', 'T3_14.80', 'T3_10.20', 'T3_10.120',
               'T3army_fullservice', 'T3civilserv_full')
```

```{r merging}
data3$T3interviewee_number <- as.numeric(data3$T3interviewee_number)

coalesce_by_column <- function(df) {
  return(coalesce(!!!as.list(df)))
}
test_data3 <- data3 %>%
  group_by(T3interviewee_number)
sum_df <- summarise_all(test_data3, coalesce_by_column)
```


```{r cleaning}
test_df <- sum_df
test_df$T3job_no <- suppressWarnings(as.numeric(test_df$T3job_no))
test_df <- test_df %>% rename(serial_number = T3interviewee_number)
df123 <- test_df %>%
  merge(data12, by = "serial_number") %>%
  select(all_of(relevant_cols))
for (col in flip_list) {
  df123 <- flip_scale(df123, col)
}
for (col in seq_len(ncol(df123))) {
  max_val <- floor(max(df123[col], na.rm = TRUE))
  for (row in seq_len(nrow(df123))) {
    if (is.na(df123[row, col])) { next }
    if (1 <= df123[row, col]) {
      if (df123[row, col] <= max_val) {
        df123[row, col] <- round(df123[row, col])
      }
      else {
        df123[row, col] <- max_val
      }
    }
    else {
      df123[row, col] <- 1
    }
  }
}
for (row in seq_len(nrow(df123))) {
  if (df123[row, "B.HELP.MENTAL"] == 3) {
    df123[row, "B.HELP.MENTAL"] <- 1
    next
  }
  if (df123[row, "B.HELP.MENTAL"] == 2) {
    df123[row, "B.HELP.MENTAL"] <- 3
    next
  }
  if (df123[row, "B.HELP.MENTAL"] == 1) {
    df123[row, "B.HELP.MENTAL"] <- 2
  }

}

success_vars <- c('serial_number','T3A8.wp.160', 'T314.10', 'T3housing_status', 'T3army_fullservice',
                  'T3civilserv_full', 'T3_10.20', 'T3_10.120', 'T3_14.80',
                  'T3_life_satisfaction_1', 'T3_life_satisfaction_5', 'T3_life_satisfaction_6',
                  'T3_life_satisfaction_7', 'T3_skills_4', 'T3_skills_8', 'T3_skills_11',
                  'T3_skills_15')




```

```{r}
till_5 <- c('FamilyTrust','PnimiaTrust','SenseCont3','SenseCont4','B.SUPPORT_4','B.SUPPORT_6','B.MAIN.OCCUPATION_8','B.LONELY_1','B.INTERNET.SUPPORT_3','B.INTERNET.SUPPORT_4')
till_2 <- c('FormalMentor','T3Adverse_Events_1','T3Adverse_Events_2','T3Adverse_Events_3','T3Adverse_Events_4','T3Adverse_Events_5','T3Adverse_Events_6','T3Adverse_Events_7','T3Adverse_Events_8','T3Adverse_Events_9','T3Adverse_Events_10','T3_ACE_1','T3_ACE_2','T3_ACE_3','T3_ACE_4','T3_ACE_5','T3_ACE_6','T3_ACE_7','T3_ACE_8','T3_ACE_9')
till_3 <- c('B.HELP.MENTAL', 'B.HELP.RELATIONS', 'B.HELP.NONPROFIT')
xdf <- df123 %>% select(c('serial_number', till_2, till_3, till_5)) %>% drop_na()
clean_df <- df123 %>%
        rename(T314.10 = 'T3T314.10') %>%
        select(c(serial_number,success_vars)) %>%
        mutate(T3army_fullservice = replace_na(T3army_fullservice, 1),
               T3civilserv_full = replace_na(T3civilserv_full, 1),
               T3A8.wp.160 = replace_na(T3A8.wp.160,1)) %>%
        drop_na() %>%
        mutate(T314.10 = (T314.10 %% 11) + 1, T3A8.wp.160 = replace(T3A8.wp.160,T3A8.wp.160==1,3))
relevant_nums_y <- clean_df$serial_number
relevant_nums_x <- xdf$serial_number
```

```{r normalization}
normalized <- function(data){
  return (apply(data,2, FUN = function(x) (x-min(x))/(max(x)-min(x))))
}
clean_df1 <- clean_df %>% apply(2, FUN = function(x) (x-min(x))/(max(x)-min(x))) %>%
 as.data.frame() %>% mutate(serial_number=relevant_nums_y)
norm_xdf <- xdf %>% apply(2, FUN = function(x) (x-min(x))/(max(x)-min(x))) %>%
        as.data.frame() %>% mutate(serial_number=relevant_nums_x)
```

```{r}
success_df <- clean_df1 %>%
  mutate(score =
           (T3A8.wp.160 * 0.03 +
             T314.10 * 0.12 +
             T3_14.80 * 0.14 +
             T3_skills_8 * 0.06 + # money - 35%
             T3army_fullservice * 0.15 +
             T3civilserv_full * 0.15 + # service - 15%
             T3_10.20 * 0.06 +
             T3_10.120 * 0.06 +
             T3_skills_11 * 0.08 + # social skills - 20%
             T3_life_satisfaction_1 * 0.03 +
             T3_life_satisfaction_5 * 0.03 +
             T3_life_satisfaction_6 * 0.03 +
             T3_life_satisfaction_7 * 0.06 + # happy - 15%
             T3_skills_4 * 0.075 +
             T3_skills_15 * 0.075)  # misc - 15%
  ) %>% select(c('serial_number','score'))
full_df <- norm_xdf %>% join(success_df) %>% drop_na() %>% select(-'serial_number')
```

```{r}
# cv2 <- crossv_mc(full_df,5)
# data.matrix(full_df[, c(till_2, till_3, till_5)])
```

```{r}
# summary(full_df$score)
accomplished_df <- full_df %>% select(c('score')) %>% group_by(score) %>% mutate(accomplished = ifelse(score > 0.7, 1, 0)) %>% group_by(accomplished) %>% summarize(amount = n())  # treshold is 0.7
```
```{r}
success_fit <- logistic_reg() %>% set_engine("glm") %>%
        fit(score ~ B.HELP.MENTAL, data = full_df, family = "binomial")
tidy(success_fit)
```
